sudo: required
services:
  - docker

before_install:
  - docker build -t diwakar031124/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true diwakar031124/docker-react npm run test

